# Data Collection Configuration
data:
  rate_limit: 1.0  # Seconds between API calls
  seasons:
    - "2023-24"
    - "2022-23"
    - "2021-22"
  min_games_played: 30
  min_minutes_per_game: 18.0

# Data Processing Configuration
processing:
  outlier_threshold: 3.0  # Standard deviations for outlier removal
  missing_value_strategy: "mean"  # Options: mean, median, zero
  scale_features: true
  fantasy_points:
    points_multiplier: 1.0
    rebound_multiplier: 1.2
    assist_multiplier: 1.5
    steal_multiplier: 3.0
    block_multiplier: 3.0
    turnover_multiplier: -1.0

# Feature Engineering Configuration
features:
  lag_features:
    enabled: true
    columns:
      - "PTS"
      - "REB"
      - "AST"
      - "FANTASY_POINTS"
    periods: [1, 3, 5, 7, 10]
  
  rolling_features:
    enabled: true
    windows: [3, 5, 7, 10]
    statistics:
      - "mean"
      - "std"
  
  momentum_features:
    enabled: true
    base_columns:
      - "FANTASY_POINTS"
      - "PTS"
      - "REB"
      - "AST"

# Model Configuration
model:
  random_state: 42
  test_size: 0.2
  validation_size: 0.1
  cross_validation_folds: 10
  
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
  
  bayesian_ridge:
    n_iter: 300
    alpha_1: 1e-6
    alpha_2: 1e-6
    lambda_1: 1e-6
    lambda_2: 1e-6
  
  adaboost:
    n_estimators: 50
    learning_rate: 1.0
  
  elastic_net:
    alpha: 1.0
    l1_ratio: 0.5
    max_iter: 1000

# Lineup Optimization Configuration
optimization:
  salary_cap: 60000
  roster_size: 8
  positions:
    PG: 1  # Point Guard
    SG: 1  # Shooting Guard
    SF: 1  # Small Forward
    PF: 1  # Power Forward
    C:  1  # Center
    G:  1  # Any Guard (PG/SG)
    F:  1  # Any Forward (SF/PF)
    UTIL: 1 # Any Position
  min_teams: 2  # Minimum number of different teams
  max_players_per_team: 4

# Paths Configuration
paths:
  data_dir: "data"
  raw_data: "data/raw"
  processed_data: "data/processed"
  models_dir: "models"
  logs_dir: "logs"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/nba_fantasy.log"